### ISSUE TITLE
Calibration Result Incorrect

### ISSUE THREAD

**Issue by rsbonini** [Wcubed/calibrate_pen_display#1]
Does not calibrate XP-Pen Tablet Artist 12 Gen 2 correctly.  Result is about 4 inches off.  Display is running portrait mode at 270 degrees rotation.

**Comment by Wcubed** [comment]
Thanks for notifying me. Turns out not only did I not consider rotated / inverted displays. But also the fine calibration had a bug that I think actually made it _worse_ than simply aligning it to the screen 😅 .
